### ISSUE TITLE
Regression error when pattern matching

### ISSUE THREAD

**Issue by sofoklis** [scala/scala3#21585] opened 2024-09-13 16:32 UTC
## 3.5.0

There seems to be a regression from scala 3.3.0 in scastie and 3.5.0

https://scastie.scala-lang.org/hmoy0V12R9eOoaX8AE3UWA

This fails with an error in 3.3.0
no error or warning in 3.5.0

## Minimized code
```
case class Example(x: Int)  

@main def ddd =
  val s: Example = Example(1)


  s match {
    case Example => println("Example" )
    //case x: Example => "println correct"
  }  
```

## Output
Error is scala 3.3.0
nothing in scala 3.5.0

when uncommenting the second case we get a warning for unreachable code in the first case 

## Expectation

should be an error in scala 3.5.0 as well

**Comment by dwijnand** [comment] 2024-09-14 01:12
Duplicate of #21582

**Closed by dwijnand** 2024-09-14 01:12 UTC
Labels: itype:bug, stat:needs triage
