### ISSUE TITLE
Merge again #21716

### ISSUE THREAD

**Issue by hamzaremmal** [scala/scala3#21743] opened 2024-10-09 14:24 UTC
#21716 was reverted since it brakes `main` when running the `[test_windows_full](https://github.com/scala/scala3/actions/runs/11240304545/job/31249339415#logs)` job. The PR needs to address the issue and be merged back !

**Comment by Gedochao** [comment] 2024-10-17 10:29
...so this is actually a duplicate of #18231, just with extra context. 🤡

**Closed** 2024-11-14 22:13 UTC
Labels: itype:bug, area:doctool, area:tasty-inspector
