### ISSUE TITLE
Implementation restriction: polymorphic function literals must have a value parameter

### ISSUE THREAD

**Issue by Swoorup** [scala/scala3#15555] opened 2022-06-30 06:51 UTC
## Compiler version

3.1.3

## Minimized code

```Scala
enum CounterInput[Response]:
  case Inc extends CounterInput[Unit]
  case Dec extends CounterInput[Unit]
  case Get extends CounterInput[Int]

def counterBehaviorK[O]: (Int, CounterInput[O]) => (Int, O) =
  case (s, CounterInput.Inc) =>
    (s + 1, ())
  case (s, CounterInput.Dec) =>
    (s + 1, ())
  case (s, CounterInput.Get) =>
    (s, s)

// not sure how to pass this behavior parameter
def doSth[S, I[_]](behavior: [O] => (S, I[O]) => (S, O)) = println("Hi")

doSth[Int, CounterInput]([O] => counterBehaviorK[O]) // Implementation restriction: polymorphic function literals must have a value parameter
doSth[Int, CounterInput](counterBehaviorK)  // Also error

```

Scastie: https://scastie.scala-lang.org/7dElqAKNQme6XFWEYckzhA

## Output

```scala
Implementation restriction: polymorphic function literals must have a value parameter
```

## Expectation
Compiles successfully

**Comment by Jasper-M** [comment] 2022-06-30 08:44
I don't think any type inference or eta-expansion is implemented yet for polymorphic function values. You have to be very explicit:
```scala
doSth[Int, CounterInput]([O] => (i: Int, c: CounterInput[O]) => counterBehaviorK(i, c))
```

**Comment by Swoorup** [comment] 2022-06-30 08:54
> I don't think any type inference or eta-expansion is implemented yet for polymorphic function values. You have to be very explicit:
> 
> ```scala
> doSth[Int, CounterInput]([O] => (i: Int, c: CounterInput[O]) => counterBehaviorK(i, c))
> ```

Ah makes sense. That explains https://github.com/lampepfl/dotty/issues/15554 too then.

**Comment by prolativ** [comment] 2022-06-30 09:56
Closing the issue then as this is not a bug but a known lack of feature

**Closed by prolativ** 2022-06-30 09:56 UTC

**Comment by jivanic-demystdata** [comment] 2024-10-31 06:29
Is this not implemented yet? I'm using Scala 3.5.2 and I hit this exact issue
If not implemented yet, shouldn't we re-open this ticket so we can track the changes in this subject?

**Comment by bishabosha** [comment] 2024-10-31 09:05
@smarter and @Sporarum did various wip on this

**Comment by Sporarum** [comment] 2024-11-09 23:29
Our work can be found in SIP-47:
https://github.com/scala/improvement-proposals/blob/main/content/polymorphic-eta-expansion.md

**Comment by SethTisue** [comment] 2024-11-10 18:19
Neither "completed" nor "not planned" is exactly right, but "not planned" seems a bit closer. (We don't normally keep open tickets for feature requests; this is primarily a bug tracker.)
