### ISSUE TITLE
Scala 3.4 with "-source:future" fails to compile xml literals

### ISSUE THREAD

**Issue by goshacodes** [scala/scala3#22223] opened 2024-12-17 08:35 UTC
## Compiler version
3.4.2
"-source:future"

## Minimized code

```Scala
val xml = <foo></foo>
```

## Output

```scala
XML literals are no longer supported. See https://docs.scala-lang.org/scala3/reference/dropped-features/xml.html
```

## Expectation
Compiles since there is no stable solution. Only some semester project from 2019 with no documentation.

Will it be merged to the language? Or will it exist as a standalone library?

**Comment by som-snytt** [comment] 2024-12-17 09:17
Semester projects are the basis of all progress!

I imagine Odersky had a semester project in the 1980s that still invigorates his current research.

**Comment by Gedochao** [comment] 2024-12-18 16:54
Hey, so this is technically a duplicate of #19100.
The migration warning you're seeing has been added in https://github.com/scala/scala3/pull/19101 and it works as expected.

Compiling with `-source:future` means you get all of the stuff that we already know would happen down the road, but there doesn't have to be a specific timeline for this.
We do plan to deprecate XML literals at some point, thus the error you're getting with `-source:future` is valid.
However, there is no alternative to `scala-xml` at this point in time.
Please notice that we haven't deprecated it in 3.6.x series, and neither do we plan to do so in 3.7.x at this point.

> Compiles since there is no stable solution.

It's `-source:future`, so there doesn't have to be a stable solution in place just yet.

> Will it be merged to the language? Or will it exist as a standalone library?

We will likely merge the interpolator back to `scala-xml` sometime in 2025. Beyond that, hard to say just yet. 
When the roadmap becomes set in stone, an announcement will be made.

Closing this, let's track this in #19100.

**Closed by Gedochao** 2024-12-18 16:54 UTC
Labels: stat:duplicate, itype:meta, area:xml
