### ISSUE TITLE
Two stacked `if` with significant identations leads to a strange seemingly unrelated error

### ISSUE THREAD

**Issue by buzden** [scala/scala3#20352] opened 2024-05-07 10:07 UTC
## Compiler version

3.3.3 LTS and 3.4.1 Next

## Minimized code

```scala
if true then
  if true then 
    println("yes")
```

https://scastie.scala-lang.org/IXEFxU30RE6xh97CK83roA

## Output

```scala
Recursive value $t needs type
```

## Expectation

Typechecks and prints "yes"

## Note

This behaviour is also provoked when `if (true)` syntax is used, i.e. without `then`. But usage of curly braces does not provoke this behaviour.

**Comment by odersky** [comment] 2024-05-08 13:28
I can't reproduce this on main.

**Comment by som-snytt** [comment] 2024-05-08 15:02
This is surely a scastie artifact, but scastie is of no use in diagnosing itself, as it does not render `-Vprint`. `$t` is its result variable when templating.

**Comment by rochala** [comment] 2024-05-09 09:35
The failure is caused by imperfect worksheet mode wrapping, which is still not working ideally with braceless syntax.

I'm moving this issue to Scastie as this is unrelated to the compiler.

**Comment by Gedochao** [comment] 2024-05-09 09:35
cc @rochala should we close this?

**Closed** 2024-05-09 09:35 UTC
Labels: itype:invalid
