### ISSUE TITLE
Opaque types are not visible when referenced by package

### ISSUE THREAD

**Issue by scf37** [scala/scala3#20038] opened 2024-03-28 06:00 UTC
## Compiler version

3.4.0

## Minimized code

```Scala
package foo

opaque type Bar = bar.Bar

object bar:
  class Bar()

  object Bar:
    def apply(): foo.Bar =
      new Bar()
```

## Output

```scala
[error] 10 |      new Bar()
[error]    |      ^^^^^^^^^
[error]    |    Found:    foo.bar.Bar
[error]    |    Required: foo.Bar²
[error]    |
[error]    |    where:    Bar  is a class in object bar
[error]    |              Bar² is a type in the top-level definitions in package foo
[error]    |
[error]    | longer explanation available when compiling with `-explain`

```

## Expectation
Successful compilation since `bar.Bar.apply` is in scope of opaque type `foo.Bar`

**Comment by som-snytt** [comment] 2024-03-28 06:55
Duplicates https://github.com/scala/scala3/issues/19609

I'll leave this open since the other PR is not merged.

**Comment by sjrd** [comment] 2024-04-02 13:18
I don't think this is a duplicate.

This is as designed, AFAICT. The top-level `opaque type` desugars into being a member of a "package object", as per the spec of top-level definitions. So it is equivalent to
```scala
package foo

object FileName$package {
  opaque type Bar = bar.Bar
}

object bar:
  class Bar()

  object Bar:
    def apply(): foo.FileName$package.Bar =
      new Bar()
```
and now it's clear that `Bar.apply` is not within the private scope of `FileName$package` where the opaque type alias would be transparent.

**Comment by Gedochao** [comment] 2024-04-02 13:20
Thanks for the clarification @sjrd.
Closing this, as this works as intended.

**Closed by Gedochao** 2024-04-02 13:20 UTC
Labels: itype:bug, itype:invalid, area:opaque-types
