### ISSUE TITLE
override modifier not allowed for abstract vars

### ISSUE THREAD

**Issue by goshacodes** [scala/scala3#18692] opened 2023-10-13 16:10 UTC
## Compiler version
3.3.0

## Minimized code
This works in scala 2, but it doesn't in scala 3
```Scala
trait X {
  var y: Int
}

trait Y extends X {
  override def y_=(x: Int) = ()
  override def y = 11
}
```

While this one is fine in both:
```scala
trait Y extends X {
  def y_=(x: Int) = ()
  def y = 11
}
```

## Output

```scala
error overriding variable y in trait X of type Int;
  method y of type => Int cannot override a mutable variable
```

Also there is a problem with concrete vars:
## Minimized code
This ones returns `override modifier required to override concrete member:`
```scala
trait X {
  var y: Int = 12
}

trait Y extends X {
  def y_=(x: Int) = ()
}
```
But when I add override modifier it gives another error `mutable variable cannot be overridden`|

```scala
trait Y extends X {
  override def y_=(x: Int) = ()
}
```

**Comment by bishabosha** [comment] 2023-10-14 19:23
I would assume that this should behave like in Scala 2

**Comment by odersky** [comment] 2023-10-14 19:31
Yes, but it's not trivial. Maybe someone could look how it was done in Scala 2 and re-implement it for 3?

**Comment by som-snytt** [comment] 2023-10-14 19:37
Relatedly https://github.com/lampepfl/dotty/issues/13019 (where the casual tweak was reverted)

**Comment by bishabosha** [comment] 2024-07-17 10:14
lets also close this as duplicate of https://github.com/scala/scala3/issues/13019

**Closed by bishabosha** 2024-07-17 10:14 UTC
Labels: itype:bug, stat:needs spec, area:refchecks
