### ISSUE TITLE
transparent inline def leaks opaque type

### ISSUE THREAD

**Issue by bishabosha** [scala/scala3#14305] opened 2022-01-20 12:39 UTC
## Compiler version

3.1.0

## Minimized code

```Scala
class Example {
  opaque type Index = Array[Int]
  transparent inline def index(using index: Index): Index = index
}

object Usage {
  def run(example: Example)(using example.Index): Unit = {
    example.index.length
  }
}
```

## Output

Compiles ok

## Expectation

`length` should not be a member of the result of `example.index` when in the scope of `Usage`

**Comment by som-snytt** [comment] 2022-01-20 16:21
Analogous to qualified private class leaking in a result type, albeit a bad analogy.

**Comment by soronpo** [comment] 2022-01-20 18:58
Could be a duplicate of https://github.com/lampepfl/dotty/issues/13461

**Comment by nicolasstucki** [comment] 2022-01-21 07:57
I added it to #13461

**Closed by nicolasstucki** 2022-01-21 07:57 UTC
Labels: itype:bug, area:inline, area:opaque-types
