### ISSUE TITLE
JVM crash: java.lang.VerifyError: Bad type on operand stack

### ISSUE THREAD

**Issue by strelec** [scala/scala3#14164] opened 2021-12-23 13:44 UTC
## Compiler version

3.1.0

## Minimized code

It seems that a combination of two factors trigger this bug:

1. skipping a parameter via named parameters
2. using for comprehension / lambda

```Scala
class Base(a: String = "x", param: String = "")

class Child extends Base(param = {
  (for(x <- Seq("a")) yield x)
  "param"
})

new Child
```

## Output

```scala
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    Playground$Child.<init>()V @25: invokedynamic
  Reason:
    Type uninitializedThis (current frame, stack[1]) is not assignable to 'Playground$Child'
```

Looks somewhat siliar to https://github.com/lampepfl/dotty/issues/2163

## Expectation

Code runs with no output.

**Comment by som-snytt** [comment] 2021-12-24 17:32
My copy/paste skills are getting rusty.
```
➜  scala i14164.scala
Child@839755f
➜  cat i14164.scala

class Base(a: String = "x", param: String = "")

class Child extends Base(param = {
  (for(x <- Seq("a")) yield x)
  "param"
})

@main def test() = println {
  new Child
}
➜  java -version
openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment (build 17.0.1+12-39)
OpenJDK 64-Bit Server VM (build 17.0.1+12-39, mixed mode, sharing)
➜  scalac -version
Scala compiler version 3.1.0 -- Copyright 2002-2021, LAMP/EPFL
```

**Comment by strelec** [comment] 2021-12-24 23:37
https://scastie.scala-lang.org/HeFyLgu5QPuWoAkfgfgRMg

**Comment by som-snytt** [comment] 2021-12-25 07:14
Reproducer
```
package api {
  package object runtime {
    trait ScastieApp extends App
  }
}

import _root_.api.runtime._
object Playground extends ScastieApp {
  class Base(a: String = "x", param: String = "")

  class Child extends Base(param = {
    (for(x <- Seq("a")) yield x)
    "param"
  })

  new Child
}
object Main {
  val playground = Playground
  def main(args: Array[String]): Unit = {
    playground.main(Array())
  }
}
```
`App` is not involved.
```
object Playground {
  class Base(a: String = "x", param: String = "")

  class Child extends Base(param = {
    (for(x <- Seq("a")) yield x)
    "param"
  })

  new Child
}
@main def test() = Playground
```
says
```
➜  scala i14164d.scala
Exception in thread "main" java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    Playground$Child.<init>()V @25: invokedynamic
  Reason:
    Type uninitializedThis (current frame, stack[1]) is not assignable to 'Playground$Child'
  Current Frame:
    bci: @25
    flags: { flagThisUninit }
    locals: { uninitializedThis }
    stack: { 'scala/collection/SeqOps', uninitializedThis }
  Bytecode:
    0000000: b200 14b6 0018 b200 1d04 bd00 1f59 0312
    0000010: 2153 b600 25b6 002b 2aba 003f 0000 b900
    0000020: 4502 0057 1247 4cb2 004a b600 4e4d 2a2c
    0000030: 2bb7 0051 b1

        at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402)
        at java.base/java.lang.Class.getMethodsRecursive(Class.java:3543)
        at java.base/java.lang.Class.getMethod0(Class.java:3529)
        at java.base/java.lang.Class.getMethod(Class.java:2225)
        at dotty.tools.scripting.ScriptingDriver.collectMainMethods$3(ScriptingDriver.scala:79)
        at dotty.tools.scripting.ScriptingDriver.$anonfun$3(ScriptingDriver.scala:88)
        at scala.collection.immutable.List.flatMap(List.scala:293)
        at dotty.tools.scripting.ScriptingDriver.detectMainClassAndMethod(ScriptingDriver.scala:89)
        at dotty.tools.scripting.ScriptingDriver.compileAndRun(ScriptingDriver.scala:34)
        at dotty.tools.scripting.Main$.main(Main.scala:43)
        at dotty.tools.MainGenericRunner$.run$1(MainGenericRunner.scala:168)
        at dotty.tools.MainGenericRunner$.main(MainGenericRunner.scala:175)
        at dotty.tools.MainGenericRunner.main(MainGenericRunner.scala)
```

**Comment by odersky** [comment] 2022-03-13 17:58
This looks like a duplicate of an issue I fixed recently. I verified that this works now.

**Comment by griggt** [comment] 2022-03-13 18:12
> I verified that this works now.

It still blows up for me:

```scala
Welcome to Scala 3.1.3-RC1-bin-SNAPSHOT-nonbootstrapped-git-5626f25 (1.8.0_292, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.

scala> class Base(a: String = "x", param: String = "")
     | 
     | class Child extends Base(param = {
     |   (for(x <- Seq("a")) yield x)
     |   "param"
     | })
     | 
     | new Child
// defined class Base
// defined class Child
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    rs$line$1$Child.<init>()V @25: invokedynamic
  Reason:
    Type uninitializedThis (current frame, stack[1]) is not assignable to 'rs$line$1$Child'
  Current Frame:
    bci: @25
    flags: { flagThisUninit }
    locals: { uninitializedThis }
    stack: { 'scala/collection/SeqOps', uninitializedThis }
  Bytecode:
    0x0000000: b200 13b6 0017 b200 1c04 bd00 1e59 0312
    0x0000010: 2053 b600 24b6 002a 2aba 003e 0000 b900
    0x0000020: 4402 0057 1246 4cb2 0049 b600 4d4d 2a2c
    0x0000030: 2bb7 0050 b1

  ... 65 elided
```

**Comment by som-snytt** [comment] 2022-03-13 18:17
It compiles but my local dotty still says

```
➜  snips ~/projects/dotty/bin/scala i14164d.scala
Exception in thread "main" java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    Playground$Child.<init>()V @25: invokedynamic
  Reason:
    Type uninitializedThis (current frame, stack[1]) is not assignable to 'Playground$Child'
  Current Frame:
    bci: @25
    flags: { flagThisUninit }
    locals: { uninitializedThis }
    stack: { 'scala/collection/SeqOps', uninitializedThis }
  Bytecode:
    0000000: b200 14b6 0018 b200 1d04 bd00 1f59 0312
    0000010: 2153 b600 25b6 002b 2aba 003f 0000 b900
    0000020: 4502 0057 1247 4cb2 004a b600 4e4d 2a2c
    0000030: 2bb7 0051 b1

        at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402)
        at java.base/java.lang.Class.getMethodsRecursive(Class.java:3543)
        at java.base/java.lang.Class.getMethod0(Class.java:3529)
        at java.base/java.lang.Class.getMethod(Class.java:2225)
        at dotty.tools.scripting.Util$.collectMainMethods$1(Util.scala:37)
        at dotty.tools.scripting.Util$.$anonfun$3(Util.scala:46)
        at scala.collection.immutable.List.flatMap(List.scala:293)
        at dotty.tools.scripting.Util$.detectMainClassAndMethod(Util.scala:47)
        at dotty.tools.scripting.ScriptingDriver.compileAndRun(ScriptingDriver.scala:28)
        at dotty.tools.scripting.Main$.main(Main.scala:45)
        at dotty.tools.MainGenericRunner$.run$1(MainGenericRunner.scala:248)
        at dotty.tools.MainGenericRunner$.main(MainGenericRunner.scala:267)
        at dotty.tools.MainGenericRunner.main(MainGenericRunner.scala)
```
where
```
➜  snips cat i14164d.scala

object Playground:
  class Base(a: String = "x", param: String = "")

  class Child extends Base(param = {
    for (x <- Seq("a")) yield x
    "param"
  })
end Playground
@main def test() = Playground
```
I have not yet re-spooled whatever insight I may have had last year. I just typed in the command at the prompt.

Oh, I guess it's a problem induced by scripting, because normally:
```
➜  snips ~/projects/dotty/bin/scalac -d /tmp i14164d.scala
resolveOverloaded List(TermRef(TermRef(ThisType(TypeRef(NoPrefix,module class scala)),object Predef),method println), TermRef(TermRef(ThisType(TypeRef(NoPrefix,module class scala)),object Predef),method println)) FunProto(Ident(Playground) => class dotty.tools.dotc.typer.ProtoTypes$CachedIgnoredProto)
resolveOverloaded.narrowedApplicable List(TermRef(TermRef(ThisType(TypeRef(NoPrefix,module class scala)),object Predef),method println))
➜  snips ~/projects/dotty/bin/scala -cp /tmp test
Playground$@62e136d3
```
where my extra debug is unrelated. I added a println out of paranoia.

**Comment by odersky** [comment] 2022-03-13 18:20
I tried with a standalone application, not a script.

**Comment by som-snytt** [comment] 2022-03-13 18:20
@griggt jinx. The other family members were shuffling out the door so I didn't hit the button first.

Also I just re-re-ran with a clean repo, it fails only with `scala` command.

**Comment by odersky** [comment] 2022-03-13 18:21
So should this be area:repl then?

**Comment by som-snytt** [comment] 2022-03-13 18:22
The script runner is not the REPL!

**Comment by griggt** [comment] 2022-03-13 18:30
@som-snytt go for it!

It seems to me that the failure only occurs in presence of the wrapper object injected by the REPL / Scastie?

**Comment by strelec** [comment] 2022-04-12 22:06
This is not just REPL, I am getting this error with production code.

**Comment by som-snytt** [comment] 2022-04-12 22:45
@strelec I will get back to this. To fail, it needs both the enclosing outer template and to force loading the `Child`. (My `@main` skipped `new Child`, but the reflective runner induced the verifier.)

I did check that `ScriptingDriver` produces the same trees, it's just running it differently.

Also the script runner is not the REPL.

**Closed** 2022-04-16 15:54 UTC
Labels: itype:bug, area:transform
