### ISSUE TITLE
Outdated "latest release" archive assets

### ISSUE THREAD

**Issue by Yewzir** [scala/scala3#21546] opened 2024-09-05 09:11 UTC
## Compiler version

These archives were taken from your latest release assets.

[scala3-3.5.0-x86_64-pc-linux.tar.gz](https://github.com/scala/scala3/releases/download/3.5.0/scala3-3.5.0-x86_64-pc-linux.tar.gz)
[scala3-3.5.0-x86_64-pc-linux.zip](https://github.com/scala/scala3/releases/download/3.5.0/scala3-3.5.0-x86_64-pc-linux.zip)

Unfortunately, both archives do not contain the advertised assets. Well, not apparently, I mean most definitely not.

## Output

```
Scala CLI version: 1.4.0
Scala version (default): 3.4.2
Your Scala CLI version is outdated. The newest version is 1.5.0
It is recommended that you update Scala CLI through the same tool or method you used for its initial installation for avoiding the creation of outdated duplicates.
```

## Expectation
```
Scala CLI version: 1.5.0
Scala version (default): 3.5.0
```

Regards
@Yewzir

**Comment by WojciechMazur** [comment] 2024-09-05 10:25
Can you tell ushow are you executing the downloaded binary? 

The bin directory contains both `scala` and `scala-cli`. 
`scala` does redirect arguments to `scala-cli` (the actual runnner) using additional arguments eg. `--prog-name scala --skip-cli-updates --cli-default-scala-version "3.5.0"`.  to make the outputs stable. 

I've checked the build logs and release branch. Everything seems to build as expected https://github.com/scala/scala3/actions/runs/10352518931/job/28658578130
@Gedochao

**Comment by Gedochao** [comment] 2024-09-05 10:41
it's actually exactly the assets that should be there.
Scala 3.5.0 is paired with Scala CLI 1.4.0.
Those warnings aren't raised if you use the runner via the `scala` script wrapper, rather than `scala-cli`.

When using Scala CLI from a Scala Next installation, it will always be a couple versions behind. This is to ensure the Scala version you have installed is fully stable with the runner. If you would rather have the newest improvements from the last stable release of Scala CLI itself, you should install Scala CLI separately, as per https://scala-cli.virtuslab.org/install

Closing this, the behaviour is as intended.

**Closed by Gedochao** 2024-09-05 10:41 UTC
Labels: itype:bug, stat:needs triage
