### ISSUE TITLE
Multi-Source Extension Overloads would be shadowed by local extensions with the same name

### ISSUE THREAD

**Issue by alphaho** [scala/scala3#21342] opened 2024-08-07 10:36 UTC
## Compiler version

- 3.4.2
- 3.5.0-RC5

## Minimized code

```Scala

object StringExtensions:
  extension (s: String) {
    def foo: String = s + " -- From StringExtensions"
  }

object IntExtensions:
  extension (i: Int) {
    def foo: String = i + " -- From IntExtensions"
  }

@main
def ThisCompiles(args: String*): Unit =
  import StringExtensions.foo
  import IntExtensions.foo

  println("Hello, world!".foo)
  println(42.foo)

@main
def ThisDoesNotCompile(args: String*): Unit =
    extension (b: Boolean)
      def foo: String = b.toString + " -- From BooleanExtensions"

    import StringExtensions.foo
    import IntExtensions.foo

    println(true.foo)
    println("Hello, world!".foo)
    println(42.foo)

```

## Output

```scala
[error] -- [E008] Not Found Error: C:\Projects\scala3-example-project\src\main\scala\Extensions.scala:30:28
[error] 30 |    println("Hello, world!".foo)
[error]    |            ^^^^^^^^^^^^^^^^^^^
[error]    |      value foo is not a member of String.
[error]    |      An extension method was tried, but could not be fully constructed:
[error]    |
[error]    |          foo("Hello, world!")
[error]    |
[error]    |          failed with:
[error]    |
[error]    |              Found:    ("Hello, world!" : String)
[error]    |              Required: Boolean
[error] -- [E008] Not Found Error: C:\Projects\scala3-example-project\src\main\scala\Extensions.scala:31:15
[error] 31 |    println(42.foo)
[error]    |            ^^^^^^
[error]    |      value foo is not a member of Int.
[error]    |      An extension method was tried, but could not be fully constructed:
[error]    |
[error]    |          foo(42)
[error]    |
[error]    |          failed with:
[error]    |
[error]    |              Found:    (42 : Int)
[error]    |              Required: Boolean
```

## Expectation
The bottom main method should compile and each call to extension method `foo` should resolves correctly as SIP-54 is merged.

**Comment by soronpo** [comment] 2024-08-07 18:07
Not a bug, but the current expected behavior.
https://contributors.scala-lang.org/t/relaxed-extension-methods-sip-54-are-not-relaxed-enough/6585

**Comment by alphaho** [comment] 2024-08-08 00:24
@soronpo thanks for pointing it out, I may have misunderstood the SIP. Is there an existing issue that we can  link to or should we keep this one open?

**Comment by soronpo** [comment] 2024-08-08 05:46
It's a closed issue, but this the original one I opened
https://github.com/scala/scala3/issues/19830

**Comment by Gedochao** [comment] 2024-08-08 07:03
Closing this, nothing to be done here.

**Closed by Gedochao** 2024-08-08 07:03 UTC
Labels: itype:invalid, area:extension-methods
