### ISSUE TITLE
Regression for method dispatch in `7mind/izumi`

### ISSUE THREAD

**Issue by WojciechMazur** [scala/scala3#21307] opened 2024-07-31 10:27 UTC
## Compiler version
Last good release: 3.6.0-RC1-bin-20240719-af933c4-NIGHTLY
First bad release: 3.6.0-RC1-bin-20240723-46ff151-NIGHTLY

Bisect scripts failed to build the compiler for some revisions, the first bad commit could be any of: 
3b3b8a77ef911825bfb0d5dc5406b641332aaa07
637b1d3dc3ddddd0cbe3e2a4ac5ec3e972a6ad05
2cfc5619b5b5089527d56b11e5189918f881bcfe
875af444d008f84dedc39cc531779c0dc76a895c
dec395be75633cc1b609dea9808b9abe4ef1bb06

## Minimized code

```Scala
trait IO2[F[_, _]]:
  def apply[A](effect: => A): F[Throwable, A] = ???

trait  syntax:
  def IO2[F[_, _], A](effect: => A)(implicit F: IO2[F]): F[Throwable, A] = ???
  def IO2[F[_, _]: IO2]: IO2[F] = ???

class Test extends syntax:
  class X[F[_, _]: IO2]:
    def fails = IO2(println("hello world!"))
    def works = IO2(println("hello world!"))(using summon[IO2[F]])

```

## Output

```scala
[error] ./src/test.scala:10:17
[error] Ambiguous overload. The overloaded alternatives of method IO2 in trait syntax with types
[error]  [F[_$5,_$6]](using evidence$1: IO2[F]): IO2[F]
[error]  [F[_$3,_$4], A](effect: => A)(implicit F: IO2[F]): F[Throwable, A]
[error] both match arguments (Unit)
[error]     def fails = IO2(println("hello world!"))
[error]                 ^^^
```

## Expectation
Should compile

**Comment by Gedochao** [comment] 2024-08-22 07:19
cc @kasiaMarek @tgodzik

**Comment by tgodzik** [comment] 2024-08-22 07:36
Wait, that's not possible. None of these commits touch the compiler itself. It's only related to the presentation compiler module

**Comment by tgodzik** [comment] 2024-08-22 07:39
Could this just be flaky?

**Comment by dwijnand** [comment] 2024-08-22 07:41
In https://github.com/scala/scala3/compare/af933c4...46ff151 https://github.com/scala/scala3/pull/21226 looks like the best candidate, with 21248 as a fallback.  Those commits mentioned don't even seem to be part of the commit range.  Is the commit message auto-generated by a script?  Because I think there's a bug in the script.

**Comment by dwijnand** [comment] 2024-08-22 07:43
Btw, this continues to not compile for me locally on main, which is a2c53a16770ffb1d2f3929b74824402300c612eb.  cc @EugeneFlesselle who's been active on the given prio change changes.

**Comment by EugeneFlesselle** [comment] 2024-08-31 10:47
The issue minimizes to:
```scala
trait P[X]
given P[Int] with {}

def foo[F]()(implicit p: P[F]): F = ???
def foo[F: P]: () => F = ???

def works = foo()(using summon[P[Int]])
def fails = foo()
```

It is introduced by [Switch mapping of context bounds to using clauses in 3.6 #21257](https://github.com/scala/scala3/pull/21257). 
The 2nd `foo` definition was/is equivalent to 
- `def foo[F](implicit ev: P[F]): () => F = ???` before the changes,
- `def foo[F](using P[F]): () => F` after the changes.

With the new version, we have the same error both before and after the changes:
```scala
-- [E051] Reference Error: tests/playground/example.scala:11:12 ----------------
11 |def fails = foo()
   |            ^^^
   |Ambiguous overload. The overloaded alternatives of method foo with types
   | [F](using x$1: P[F]): () => F
   | [F]()(implicit p: P[F]): F
   |both match arguments ()
   |----------------------------------------------------------------------------
   | Explanation (enabled by `-explain`)
   |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   | There are 2 methods that could be referenced as the compiler knows too little
   | about the expected type.
   | You may specify the expected type e.g. by
   | - assigning it to a value with a specified type, or
   | - adding a type ascription as in instance.myMethod: String => Int
    ----------------------------------------------------------------------------
```

I believe this is an intended change in behavior of #21257. Unless it is causing too many regressions, this should probably be a won't-fix. \cc @WojciechMazur @Gedochao

**Comment by Gedochao** [comment] 2024-09-03 10:25
> I believe this is an intended change in behavior of https://github.com/scala/scala3/pull/21257. Unless it is causing too many regressions, this should probably be a won't-fix.

@EugeneFlesselle agreed. Closing this as `won'tfix`

**Closed by Gedochao** 2024-09-03 10:25 UTC
Labels: itype:bug, area:typer, stat:wontfix, area:overloading, regression
