### ISSUE TITLE
`NamedTuple.Names` and `NamedTuple.DropNames` not working as expected

### ISSUE THREAD

**Issue by kavedaa** [scala/scala3#21194] opened 2024-07-14 12:42 UTC
## Compiler version

3.5.0-RC3

## Minimized code

```Scala
//> using scala 3.5.0-RC3, 3.nightly

import scala.language.experimental.namedTuples

object Test:

  val bar = (a = "hello", b = 1)

  summon[NamedTuple.Names[bar.type] <:< ("a", "b")]
    
  summon[NamedTuple.DropNames[bar.type] <:< (String, Int)]
```

## Output

```
Compiling project (Scala 3.5.0-RC3, JVM (8))
[error] .\test.scala:9:52
[error] Cannot prove that NamedTupleDecomposition.Names[(Test.bar : (a : String, b : Int))] <:< (("a" : String), ("b" : String)).
[error]
[error] Note: a match type could not be fully reduced:
[error]
[error]   trying to reduce  NamedTupleDecomposition.Names[(Test.bar : (a : String, b : Int))]
[error]   failed since selector (Test.bar : (a : String, b : Int))
[error]   does not match  case NamedTuple.NamedTuple[n, _] => n
[error]   and cannot be shown to be disjoint from it either.
[error]   summon[NamedTuple.Names[bar.type] <:< ("a", "b")]
[error]                                                    ^
[error] .\test.scala:11:59
[error] Cannot prove that NamedTupleDecomposition.DropNames[(Test.bar : (a : String, b : Int))] <:< (String, Int).
[error]
[error] Note: a match type could not be fully reduced:
[error]
[error]   trying to reduce  NamedTupleDecomposition.DropNames[(Test.bar : (a : String, b : Int))]
[error]   failed since selector (Test.bar : (a : String, b : Int))
[error]   does not match  case NamedTuple.NamedTuple[_, x] => x
[error]   and cannot be shown to be disjoint from it either.
[error]   summon[NamedTuple.DropNames[bar.type] <:< (String, Int)]
[error]                                                           ^
Error compiling project (Scala 3.5.0-RC3, JVM (8))
```

## Expectation

Successful compilation.

**Comment by WojciechMazur** [comment] 2024-07-14 12:59
You're using the using directives incorrectly, it should be just 
```scala
//> using scala 3.nightly
```
Seems like the directives parser in scala-cli is not warning about invalid values here. It's using the 1st valid value instead which in this case is 3.5.0-RC3

**Comment by bishabosha** [comment] 2024-07-14 14:18
this is a duplicate of https://github.com/scala/scala3/issues/20453

**Closed by bishabosha** 2024-07-14 14:18 UTC
Labels: itype:bug, stat:needs triage

**Comment by kavedaa** [comment] 2024-11-24 17:03
What does "not planned" mean here? I'm not able do draw any conclusions from the linked issue. Does it mean that this is not supposed to work?
