### ISSUE TITLE
Parameter untupling can be prevented with indirection

### ISSUE THREAD

**Issue by coreywoodfield** [scala/scala3#21778] opened 2024-10-16 00:20 UTC
## Compiler version

3.3.4

## Minimized code

doesn't work:
```scala
trait Foo {
  type T <: Tuple
  type Mapped = Tuple.Map[T, Option]

  def map[A](f: Mapped => A): Unit = ???
}
class Bar extends Foo {
  override type T = (Int, String)
  // doesn't compile
  map { (int, string) =>
    ()
  }
}
```

works:
```scala
trait Foo {
  type T <: Tuple
  
  def map[A](f: Tuple.Map[T, Option] => A): Unit = ???
}
class Bar extends Foo {
  override type T = (Int, String)
  // compiles fine
  map { (int, string) =>
    ()
  }
}
```

## Output

```scala
-- [E086] Syntax Error: .../Test.scala:39:22 
39 |  map { (int, string) =>
   |        ^
   |        Wrong number of parameters, expected: 1
40 |    ()
   |----------------------------------------------------------------------------
   | Explanation (enabled by `-explain`)
   |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   | The function literal
   |
   |     (int, string) =>
   |   {
   |     ()
   |   }
   |
   | has 2 parameters. But the expected type
   |
   |     Bar.this.Map => Unit
   |
   | requires a function with 1 parameters.
    ----------------------------------------------------------------------------
one error found
```

## Expectation

I expect parameter untupling to occur regardless of type indirection, as long as the type can be fully resolved where the parameter untupling should occur. Instead, parameter untupling does not always occur. I think the alias and the `match` type are both playing a role here: simply having two aliases that refer to a concrete tuple type (`type T = (Int, String)`, `type X = T`) does not prevent parameter untupling

**Comment by WojciechMazur** [comment] 2024-10-16 07:30
This issue was fixed in Scala Next releases, to be exact it now works correctly since release 3.5.0. 
Scala 3.3.4 contains all safe-to-backport changes introduced until Scala 3.5.1. It means that we're not able to fix this issue in the LTS without breaking binary/source compatibility in the LTS line, introducing new regressions, or it depended on other changes that failed this criteria.

**Comment by Gedochao** [comment] 2024-10-16 10:41
Seems like it's a `wontfix` for the LTS.
Closing this, nothing to do here.

**Closed by Gedochao** 2024-10-16 10:41 UTC
Labels: itype:bug, area:typer, area:match-types, stat:fixed in next

**Comment by som-snytt** [comment] 2024-10-16 12:29
Duplicates https://github.com/scala/scala3/issues/19821
